# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hw2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1024, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 768))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(55, 55, 55);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textArea_log = QtWidgets.QTextBrowser(self.centralwidget)
        self.textArea_log.setGeometry(QtCore.QRect(0, 660, 1031, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textArea_log.setFont(font)
        self.textArea_log.setStyleSheet("color: rgb(0, 255, 0);")
        self.textArea_log.setReadOnly(True)
        self.textArea_log.setObjectName("textArea_log")
        self.picture_devidedLine = QtWidgets.QGraphicsView(self.centralwidget)
        self.picture_devidedLine.setGeometry(QtCore.QRect(0, 650, 1031, 20))
        self.picture_devidedLine.setStyleSheet("background-color: rgb(162, 162, 162);")
        self.picture_devidedLine.setObjectName("picture_devidedLine")
        self.plot_trainingData_pre = QtWidgets.QWidget(self.centralwidget)
        self.plot_trainingData_pre.setGeometry(QtCore.QRect(340, 20, 331, 301))
        self.plot_trainingData_pre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plot_trainingData_pre.setObjectName("plot_trainingData_pre")
        self.plot_testData_pre = QtWidgets.QWidget(self.centralwidget)
        self.plot_testData_pre.setGeometry(QtCore.QRect(680, 20, 331, 301))
        self.plot_testData_pre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plot_testData_pre.setObjectName("plot_testData_pre")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 500, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(200,200, 200);\n"
"background-color: rgb(100,100, 100);")
        self.pushButton.setObjectName("pushButton")
        self.progressBar_progress = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_progress.setGeometry(QtCore.QRect(0, 640, 1071, 23))
        self.progressBar_progress.setProperty("value", 0)
        self.progressBar_progress.setObjectName("progressBar_progress")
        self.label_input = QtWidgets.QLabel(self.centralwidget)
        self.label_input.setGeometry(QtCore.QRect(10, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_input.setFont(font)
        self.label_input.setStyleSheet("color: rgb(162, 162, 162);")
        self.label_input.setObjectName("label_input")
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        self.label_output.setGeometry(QtCore.QRect(10, 200, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_output.setFont(font)
        self.label_output.setStyleSheet("color: rgb(162, 162, 162);")
        self.label_output.setObjectName("label_output")
        self.label_trainingData = QtWidgets.QLabel(self.centralwidget)
        self.label_trainingData.setGeometry(QtCore.QRect(30, 230, 91, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_trainingData.setFont(font)
        self.label_trainingData.setStyleSheet("color: rgb(162, 162, 162);")
        self.label_trainingData.setAlignment(QtCore.Qt.AlignCenter)
        self.label_trainingData.setObjectName("label_trainingData")
        self.label_filename = QtWidgets.QLabel(self.centralwidget)
        self.label_filename.setGeometry(QtCore.QRect(20, 40, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_filename.setFont(font)
        self.label_filename.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_filename.setAutoFillBackground(False)
        self.label_filename.setStyleSheet("color: rgb(162, 162, 162);")
        self.label_filename.setTextFormat(QtCore.Qt.AutoText)
        self.label_filename.setScaledContents(False)
        self.label_filename.setAlignment(QtCore.Qt.AlignCenter)
        self.label_filename.setObjectName("label_filename")
        self.label_testData = QtWidgets.QLabel(self.centralwidget)
        self.label_testData.setGeometry(QtCore.QRect(30, 260, 91, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_testData.setFont(font)
        self.label_testData.setStyleSheet("color: rgb(162, 162, 162);")
        self.label_testData.setAlignment(QtCore.Qt.AlignCenter)
        self.label_testData.setObjectName("label_testData")
        self.label_weight = QtWidgets.QLabel(self.centralwidget)
        self.label_weight.setGeometry(QtCore.QRect(30, 290, 91, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_weight.setFont(font)
        self.label_weight.setStyleSheet("color: rgb(162, 162, 162);")
        self.label_weight.setAlignment(QtCore.Qt.AlignCenter)
        self.label_weight.setObjectName("label_weight")
        self.label_studyScale = QtWidgets.QLabel(self.centralwidget)
        self.label_studyScale.setGeometry(QtCore.QRect(20, 70, 151, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_studyScale.setFont(font)
        self.label_studyScale.setStyleSheet("color: rgb(162, 162, 162);")
        self.label_studyScale.setScaledContents(False)
        self.label_studyScale.setAlignment(QtCore.Qt.AlignCenter)
        self.label_studyScale.setObjectName("label_studyScale")
        self.label_convergeCondition = QtWidgets.QLabel(self.centralwidget)
        self.label_convergeCondition.setGeometry(QtCore.QRect(30, 100, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_convergeCondition.setFont(font)
        self.label_convergeCondition.setStyleSheet("color: rgb(162, 162, 162);")
        self.label_convergeCondition.setAlignment(QtCore.Qt.AlignCenter)
        self.label_convergeCondition.setObjectName("label_convergeCondition")
        self.widget_for_InputBackground = QtWidgets.QWidget(self.centralwidget)
        self.widget_for_InputBackground.setGeometry(QtCore.QRect(10, 20, 321, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_for_InputBackground.sizePolicy().hasHeightForWidth())
        self.widget_for_InputBackground.setSizePolicy(sizePolicy)
        self.widget_for_InputBackground.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_for_InputBackground.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.widget_for_InputBackground.setObjectName("widget_for_InputBackground")
        self.widget_for_InputBackground_2 = QtWidgets.QWidget(self.widget_for_InputBackground)
        self.widget_for_InputBackground_2.setGeometry(QtCore.QRect(10, 10, 301, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_for_InputBackground_2.sizePolicy().hasHeightForWidth())
        self.widget_for_InputBackground_2.setSizePolicy(sizePolicy)
        self.widget_for_InputBackground_2.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_for_InputBackground_2.setStyleSheet("background-color: rgb(55, 55, 55);")
        self.widget_for_InputBackground_2.setObjectName("widget_for_InputBackground_2")
        self.lineEdit_studyScale = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_studyScale.setGeometry(QtCore.QRect(170, 70, 141, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_studyScale.setFont(font)
        self.lineEdit_studyScale.setStyleSheet("color: rgb(162, 162, 162);\n"
"background-color: rgb(80, 80, 80);")
        self.lineEdit_studyScale.setObjectName("lineEdit_studyScale")
        self.lineEdit_convergeCondition = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_convergeCondition.setGeometry(QtCore.QRect(170, 100, 141, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_convergeCondition.sizePolicy().hasHeightForWidth())
        self.lineEdit_convergeCondition.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_convergeCondition.setFont(font)
        self.lineEdit_convergeCondition.setStyleSheet("color: rgb(162, 162, 162);\n"
"background-color: rgb(80, 80, 80);")
        self.lineEdit_convergeCondition.setObjectName("lineEdit_convergeCondition")
        self.label_trainingPercent = QtWidgets.QLabel(self.centralwidget)
        self.label_trainingPercent.setGeometry(QtCore.QRect(130, 230, 181, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_trainingPercent.setFont(font)
        self.label_trainingPercent.setStyleSheet("color: rgb(162, 162, 162);")
        self.label_trainingPercent.setObjectName("label_trainingPercent")
        self.label_testPercent = QtWidgets.QLabel(self.centralwidget)
        self.label_testPercent.setGeometry(QtCore.QRect(130, 260, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_testPercent.setFont(font)
        self.label_testPercent.setStyleSheet("color: rgb(162, 162, 162);")
        self.label_testPercent.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_testPercent.setObjectName("label_testPercent")
        self.label_weightValue = QtWidgets.QLabel(self.centralwidget)
        self.label_weightValue.setGeometry(QtCore.QRect(130, 290, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_weightValue.setFont(font)
        self.label_weightValue.setStyleSheet("color: rgb(162, 162, 162);")
        self.label_weightValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_weightValue.setObjectName("label_weightValue")
        self.comboBox_filename = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_filename.setGeometry(QtCore.QRect(170, 40, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_filename.setFont(font)
        self.comboBox_filename.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.comboBox_filename.setStyleSheet("color: rgb(162, 162, 162);\n"
"background-color: rgb(80, 80, 80);")
        self.comboBox_filename.setObjectName("comboBox_filename")
        self.widget_for_OutputBackground = QtWidgets.QWidget(self.centralwidget)
        self.widget_for_OutputBackground.setGeometry(QtCore.QRect(10, 210, 321, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_for_OutputBackground.sizePolicy().hasHeightForWidth())
        self.widget_for_OutputBackground.setSizePolicy(sizePolicy)
        self.widget_for_OutputBackground.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_for_OutputBackground.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.widget_for_OutputBackground.setObjectName("widget_for_OutputBackground")
        self.widget_for_OutputBackground_2 = QtWidgets.QWidget(self.widget_for_OutputBackground)
        self.widget_for_OutputBackground_2.setGeometry(QtCore.QRect(10, 10, 301, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_for_OutputBackground_2.sizePolicy().hasHeightForWidth())
        self.widget_for_OutputBackground_2.setSizePolicy(sizePolicy)
        self.widget_for_OutputBackground_2.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_for_OutputBackground_2.setStyleSheet("background-color: rgb(55, 55, 55);")
        self.widget_for_OutputBackground_2.setObjectName("widget_for_OutputBackground_2")
        self.label_RMSE = QtWidgets.QLabel(self.centralwidget)
        self.label_RMSE.setGeometry(QtCore.QRect(30, 320, 91, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_RMSE.setFont(font)
        self.label_RMSE.setStyleSheet("color: rgb(162, 162, 162);")
        self.label_RMSE.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RMSE.setObjectName("label_RMSE")
        self.label_RMSEValue = QtWidgets.QLabel(self.centralwidget)
        self.label_RMSEValue.setGeometry(QtCore.QRect(130, 320, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_RMSEValue.setFont(font)
        self.label_RMSEValue.setStyleSheet("color: rgb(162, 162, 162);")
        self.label_RMSEValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RMSEValue.setObjectName("label_RMSEValue")
        self.label_thetaValue = QtWidgets.QLabel(self.centralwidget)
        self.label_thetaValue.setGeometry(QtCore.QRect(130, 350, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_thetaValue.setFont(font)
        self.label_thetaValue.setStyleSheet("color: rgb(162, 162, 162);")
        self.label_thetaValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_thetaValue.setObjectName("label_thetaValue")
        self.label_theta = QtWidgets.QLabel(self.centralwidget)
        self.label_theta.setGeometry(QtCore.QRect(30, 350, 91, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_theta.setFont(font)
        self.label_theta.setStyleSheet("color: rgb(162, 162, 162);")
        self.label_theta.setAlignment(QtCore.Qt.AlignCenter)
        self.label_theta.setObjectName("label_theta")
        self.label_kValue = QtWidgets.QLabel(self.centralwidget)
        self.label_kValue.setGeometry(QtCore.QRect(170, 130, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_kValue.setFont(font)
        self.label_kValue.setStyleSheet("color: rgb(162, 162, 162);")
        self.label_kValue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kValue.setObjectName("label_kValue")
        self.label_k = QtWidgets.QLabel(self.centralwidget)
        self.label_k.setGeometry(QtCore.QRect(30, 130, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_k.setFont(font)
        self.label_k.setStyleSheet("color: rgb(162, 162, 162);")
        self.label_k.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k.setObjectName("label_k")
        self.plot_trainingData_after = QtWidgets.QWidget(self.centralwidget)
        self.plot_trainingData_after.setGeometry(QtCore.QRect(340, 330, 331, 301))
        self.plot_trainingData_after.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plot_trainingData_after.setObjectName("plot_trainingData_after")
        self.plot_testData_after = QtWidgets.QWidget(self.centralwidget)
        self.plot_testData_after.setGeometry(QtCore.QRect(680, 330, 331, 301))
        self.plot_testData_after.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plot_testData_after.setObjectName("plot_testData_after")
        self.widget_for_OutputBackground.raise_()
        self.widget_for_InputBackground.raise_()
        self.progressBar_progress.raise_()
        self.picture_devidedLine.raise_()
        self.textArea_log.raise_()
        self.plot_trainingData_pre.raise_()
        self.plot_testData_pre.raise_()
        self.pushButton.raise_()
        self.label_input.raise_()
        self.label_output.raise_()
        self.label_trainingData.raise_()
        self.label_filename.raise_()
        self.label_testData.raise_()
        self.label_weight.raise_()
        self.label_studyScale.raise_()
        self.label_convergeCondition.raise_()
        self.lineEdit_studyScale.raise_()
        self.lineEdit_convergeCondition.raise_()
        self.label_trainingPercent.raise_()
        self.label_testPercent.raise_()
        self.label_weightValue.raise_()
        self.comboBox_filename.raise_()
        self.label_RMSE.raise_()
        self.label_RMSEValue.raise_()
        self.label_thetaValue.raise_()
        self.label_theta.raise_()
        self.label_kValue.raise_()
        self.label_k.raise_()
        self.plot_trainingData_after.raise_()
        self.plot_testData_after.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked['bool'].connect(MainWindow.start_calculate)
        self.comboBox_filename.activated['QString'].connect(MainWindow.preview_picture)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "類神經網路 作業2 ── RBFN姬"))
        self.textArea_log.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'PMingLiU\';\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.label_input.setText(_translate("MainWindow", "I n p u t"))
        self.label_output.setText(_translate("MainWindow", "O u t p u t"))
        self.label_trainingData.setText(_translate("MainWindow", "訓練辨識度："))
        self.label_filename.setText(_translate("MainWindow", "檔名"))
        self.label_testData.setText(_translate("MainWindow", "測試辨識度："))
        self.label_weight.setText(_translate("MainWindow", "鍵結值(W)："))
        self.label_studyScale.setText(_translate("MainWindow", "學習率"))
        self.label_convergeCondition.setText(_translate("MainWindow", "收斂條件(迭代次數)"))
        self.label_trainingPercent.setText(_translate("MainWindow", "???%"))
        self.label_testPercent.setText(_translate("MainWindow", "???%"))
        self.label_weightValue.setText(_translate("MainWindow", "[?, ?]"))
        self.label_RMSE.setText(_translate("MainWindow", "RMSE："))
        self.label_RMSEValue.setText(_translate("MainWindow", "????"))
        self.label_thetaValue.setText(_translate("MainWindow", "????"))
        self.label_theta.setText(_translate("MainWindow", "theta："))
        self.label_kValue.setText(_translate("MainWindow", "????"))
        self.label_k.setText(_translate("MainWindow", "k"))

